### ISSUE TITLE
Does this library work?

### ISSUE THREAD

**Issue by lemkoleg** [DitchOoM/websocket#5]
Does this library work? What version can I specify in build.gradle? Does the socket support binary messaging?

**Comment by thebehera** [comment]
Does this library work?
- Yes it should. It has tons of integration tests including validation with the Autobahn test suite
What version can I specify in build.gradle?
- You can find the latest version here https://central.sonatype.com/artifact/com.ditchoom/websocket
Does the socket support binary messaging?
- Yes you can [call this function](https://github.com/DitchOoM/websocket/blob/main/src/commonMain/kotlin/com/ditchoom/websocket/WebSocketClient.kt#L20). Here you can pass a [ReadBuffer or a Platform agnostic buffer](https://github.com/DitchOoM/websocket/blob/main/src/commonMain/kotlin/com/ditchoom/websocket/WebSocketClient.kt#L20).
